### PR TITLE
Fix create mod compatibility (Fabric)

### PR DESCRIPTION
**Pull request by Shulej**
This should allow newer builds of the create mod to work with this mod

### CODE REVIEW

**Comment by MrStickyPiston** [comment]
Thank you for the contribution, i can not test this at the moment but it looks good. I will merge this after it builds succesfully, but publishing to modrinth and curseforge will take some time.

**Comment by MrStickyPiston** [comment]
It seems like a new create version broke the mod.

**Comment by MrStickyPiston** [comment]
Nvm its just GitHub actions that broke.

**Comment by Shulej** [comment]
yeah, I edited the `fabric.mod.json` in the .jar of the mod, tested with the newest version of create, everything seemed to be working correctly

**Comment by MrStickyPiston** [comment]
Fixed the build process, merging!

**Pull request merged**
